#!/bin/sh

# Colours
RED="$(tput setaf 1 bold)"
GREEN="$(tput setaf 2 bold)"
YELLOW="$(tput setaf 3 bold)"
MAGENTA="$(tput setaf 5 bold)"
NC="$(tput sgr0)"

BLUE="$(tput setaf 14 bold)"
PINK="$(tput setaf 217 bold)"
WHITE="$(tput setaf 7 bold)"

# Sys info
NAME="$(whoami)@$(uname -n)"
OS="$(awk -F= '$1 == "NAME" {gsub(/"/, "", $2); print $2}' /etc/os-release)"
KERNEL=$(uname -r)
SHELL=$(basename $SHELL)
UPTIME="$(awk -F'( |,|:)+' '{printf "%d hours, %d minutes\n", $1/3600, ($1%3600)/60}' /proc/uptime)"
MEMORY="$(free -m | awk 'NR==2{print $3 "M / " $2 "M"}')"


if [ -z "$1" ]
then cat<<BERRY
${GREEN}      (    ((       ${MAGENTA}${NAME}${GREEN}
    ((  (((  ((     
    ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC}      ${OS}${GREEN}
   ${RED}##${YELLOW}%${RED}#######${YELLOW}%${RED}##    ${RED}Kernel:${NC}  ${KERNEL}${RED}
   ######${YELLOW}%${RED}####${YELLOW}%${RED}#    ${RED}Shell:${NC}   ${SHELL}${RED}
    ##${YELLOW}%${RED}####${YELLOW}%${RED}###     ${RED}Uptime:${NC}  ${UPTIME}${RED}
     ####${YELLOW}%${RED}####      ${RED}Memory:${NC}  ${MEMORY}${RED}
       ##### 
         #${NC}
BERRY
elif [ "$1" = "--trans" ]
then cat<<BERRY
${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
    ((  (((  ((     
    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
       #####
         # ${NC}
BERRY
else printf "${RED}ERROR:${NC} Unknown argument: ${1}\nCurrently known arguments: --trans\n";exit 1
fi
