#!/bin/bash

# Colours
RED='\e[1;31m'
GREEN='\e[1;32m'
MAGENTA='\e[1;35m'
YELLOW='\e[1;33m'
NC='\e[0m'

BLUE='\x1b[1;96m'
PINK='\x1b[1;38;2;245;169;184m'
WHITE='\x1b[1;97m'

# Sys info
NAME="$(whoami)@$(uname -n)"
OS=$(awk -F= '$1 == "NAME" {gsub(/"/, "", $2); print $2}' /etc/os-release)
KERNEL=$(uname -r)
SHELL=$(basename $SHELL)
UPTIME="$(uptime -p | sed 's/up //')"
MEMORY="$(free -m | awk 'NR==2{print $3 "M / " $2 "M"}')"

if [ ! -z "$1" ]; then
  if [ "$1" != "--trans" ]; then
    echo -e "${RED}ERROR:${NC} Unknown argument: ${1}, known arguments: --trans"
    exit 1
  fi

OUTPUT="$(
cat << BERRY
${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
    ((  (((  ((     
    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
       #####
         # ${NC}
BERRY
)"

  echo -e "${OUTPUT}"
  exit 0
fi

OUTPUT="$(
cat << BERRY
${GREEN}      (    ((       ${MAGENTA}${NAME}${GREEN}
    ((  (((  ((     
    ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC}      ${OS}${GREEN}
   ${RED}##${YELLOW}%${RED}#######${YELLOW}%${RED}##    ${RED}Kernel:${NC}  ${KERNEL}${RED}
   ######${YELLOW}%${RED}####${YELLOW}%${RED}#    ${RED}Shell:${NC}   ${SHELL}${RED}
    ##${YELLOW}%${RED}####${YELLOW}%${RED}###     ${RED}Uptime:${NC}  ${UPTIME}${RED}
     ####${YELLOW}%${RED}####      ${RED}Memory:${NC}  ${MEMORY}${RED}
       ##### 
         #${NC}
BERRY
)"

echo -e "${OUTPUT}"
