#!/bin/bash

# Colours
RED='\e[1;31m'
GREEN='\e[1;32m'
MAGENTA='\e[1;35m'
WHITE='\e[1;33m'
NC='\e[0m'

BLUE='\x1b[1;96m'
PINK='\x1b[1;38;2;245;169;184m'
WHITE='\x1b[1;97m'

# Android Info
android_version=$(getprop ro.build.version.release)
device_model=$(getprop ro.product.model)
manufacturer=$(getprop ro.product.manufacturer)

# Sys info
NAME="$(whoami)@$(uname -n)"
OS=$android_version
PHONE=$manufacturer
MODEL=$device_model
KERNEL=$(uname -r)
SHELL=$(basename $SHELL)
UPTIME="$(uptime -p | sed 's/up //')"
MEMORY="$(free -m | awk 'NR==2{print $3 "M / " $2 "M"}')"

if [ ! -z "$1" ]; then
  if [ "$1" != "--trans" ]; then
    echo -e "${RED}ERROR:${NC} Unknown argument: ${1}, currently known arguments: --trans"
    exit 1
  fi

OUTPUT="$(
cat << BERRY
${BLUE}      8    8${NC}       ${MAGENTA}${NAME}${PINK}
    88  888  88     
    ###((((###${NC}      ${RED}OS:${NC}  Android ${OS}${WHITE}
   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
       #####        ${RED}Phone:${NC}   ${PHONE}${BLUE}
         # ${NC}         ${RED}Model:${NC}   ${MODEL}${BLUE}
BERRY
)"

  echo -e "${OUTPUT}"
  exit 0
fi

OUTPUT="$(
cat << BERRY
${GREEN}      8    88       ${MAGENTA}${NAME}${GREEN}
    88  888  88     
    ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC} Android ${OS}${GREEN}
   ${RED}##${WHITE}%${RED}#######${WHITE}%${RED}##    ${RED}Kernel:${NC}  ${KERNEL}${RED}
   ######${WHITE}%${RED}####${WHITE}%${RED}#    ${RED}Shell:${NC}   ${SHELL}${RED}
    ##${WHITE}%${RED}####${WHITE}%${RED}###     ${RED}Uptime:${NC}  ${UPTIME}${RED}
     ####${WHITE}%${RED}####      ${RED}Memory:${NC}  ${MEMORY}${RED}
       #####        ${RED}Phone:${NC}   ${PHONE}${RED}   
         #${NC}          ${RED}Model:${NC}   ${MODEL}${RED}
BERRY
)"

echo -e "${OUTPUT}"
